version: "3.8"
services:
  smartmirror:
    image: zailregistry.azurecr.io/senj/sharpmirror:#{BUILD_ID}#
    container_name: smartmirror
    restart: always
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=
      - WeatherConfiguration__ApiKey=
      - FuelConfiguration__ApiKey=
      - SpotifyConfiguration__ClientSecret=
      - CalendarConfiguration__CalendarUrl=
      - FitbitConfiguration__ClientSecret=
      - RedisConfiguration__Configuration=
      - BringConfiguration__Email=
      - BringConfiguration__Password=
      - RouteConfiguration__ApiKey=
      - SpeechRecognitionConfiguration__SpeechApiSubscriptionKey=
      - SpeechRecognitionConfiguration__LuisAppId=
      - SpeechRecognitionConfiguration__LuisSubscriptionKey=
      - SpeechRecognitionConfiguration__LuisEndpoint=
      - GoogleApiConfiguration__ClientId=
      - GoogleApiConfiguration__ClientSecret=